eureka:
  client:
    service-url:
      defaultZone: http://10.160.0.4:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.example: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

jwt:
  secret: MySuperDuperSecretKeyForJwtAuthenticationWhichIsVeryLongAndSecure123456
  expiration: 900000
  refresh-expiration: 604800000