server:
  port: 8084

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:

          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**

            - id: salon-service
              uri: lb://SALON-SERVICE
              predicates:
                - Path=/api/v1/salons/**

            - id: appointment-service
              uri: lb://APPOINTMENT-SERVICE
              predicates:
                - Path=/api/v1/appointments/**

          default-filters:
            - PreserveHostHeader
            - AuthenticationFilter

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:5173"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true

eureka:
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    gateway:
      access: unrestricted